
package com.oracle.xmlns.irm.rights.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ContextInstanceAlreadyExistsFault", targetNamespace = "http://xmlns.oracle.com/irm/rights/wsdl")
public class ContextInstanceAlreadyExistsFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.oracle.xmlns.irm.rights.ContextInstanceAlreadyExistsFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ContextInstanceAlreadyExistsFault(String message, com.oracle.xmlns.irm.rights.ContextInstanceAlreadyExistsFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ContextInstanceAlreadyExistsFault(String message, com.oracle.xmlns.irm.rights.ContextInstanceAlreadyExistsFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.xmlns.irm.rights.ContextInstanceAlreadyExistsFault
     */
    public com.oracle.xmlns.irm.rights.ContextInstanceAlreadyExistsFault getFaultInfo() {
        return faultInfo;
    }

}
