
package com.oracle.xmlns.irm.rights.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * 
 *             Context related operations. The context related operations cover the tasks that a context manager would typically perform on a Context Instance. This includes altering Context Instance names and descriptions, specifying the set of Context Instance managers and setting Context Instance level Item Code exclusions. Journal operations are also included. The content journal contains a log of all activity performed on Context sealed content. This includes actions performed while off-line as well as on-line. It includes actions performed on the desktop as well as actions perform on the server. The journal is filled automatically when users perform actions on content, e.g. when content is opened or printed. Failed actions are also added to the journal.
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ContextOperationsService", targetNamespace = "http://xmlns.oracle.com/irm/rights/wsdl", wsdlLocation = "http://ium-vbox-win2k8:16100/irm_services/context_operations?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Firm%2Frights%2Fwsdl%7DContextOperationsService")
public class ContextOperationsService
    extends Service
{

    private final static URL CONTEXTOPERATIONSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.xmlns.irm.rights.wsdl.ContextOperationsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.oracle.xmlns.irm.rights.wsdl.ContextOperationsService.class.getResource(".");
            url = new URL(baseUrl, "http://ium-vbox-win2k8:16100/irm_services/context_operations?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Firm%2Frights%2Fwsdl%7DContextOperationsService");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ium-vbox-win2k8:16100/irm_services/context_operations?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Firm%2Frights%2Fwsdl%7DContextOperationsService', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONTEXTOPERATIONSSERVICE_WSDL_LOCATION = url;
    }

    public ContextOperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContextOperationsService() {
        super(CONTEXTOPERATIONSSERVICE_WSDL_LOCATION, new QName("http://xmlns.oracle.com/irm/rights/wsdl", "ContextOperationsService"));
    }

    /**
     * 
     * @return
     *     returns ContextOperations
     */
    @WebEndpoint(name = "ContextOperations")
    public ContextOperations getContextOperations() {
        return super.getPort(new QName("http://xmlns.oracle.com/irm/rights/wsdl", "ContextOperations"), ContextOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContextOperations
     */
    @WebEndpoint(name = "ContextOperations")
    public ContextOperations getContextOperations(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/irm/rights/wsdl", "ContextOperations"), ContextOperations.class, features);
    }

}
