package com.oracle.xmlns.irm.rights.wsdl;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.0.0.6017

public class DocumentRoleOperationsClient
{
  public static void main(String [] args)
  {
    DocumentRoleOperationsService documentRoleOperationsService = new DocumentRoleOperationsService();
    DocumentRoleOperations documentRoleOperations = documentRoleOperationsService.getDocumentRoleOperations();
    // Add your code to call the desired methods.
  }
}
