
package com.oracle.xmlns.irm.rights.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * 
 *             Document role operations. The document role operations include role management operations such as creating, editing and copying roles. The document role operations also include role assignment roles and re-assignment.
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentRoleOperationsService", targetNamespace = "http://xmlns.oracle.com/irm/rights/wsdl", wsdlLocation = "https://ium-vbox-win2k8:16101/irm_services/document_role_operations?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Firm%2Frights%2Fwsdl%7DDocumentRoleOperationsService")
public class DocumentRoleOperationsService
    extends Service
{

    private final static URL DOCUMENTROLEOPERATIONSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.xmlns.irm.rights.wsdl.DocumentRoleOperationsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.oracle.xmlns.irm.rights.wsdl.DocumentRoleOperationsService.class.getResource(".");
            url = new URL(baseUrl, "http://ium-vbox-win2k8:16100/irm_services/document_role_operations?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Firm%2Frights%2Fwsdl%7DDocumentRoleOperationsService");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ium-vbox-win2k8:16100/irm_services/document_role_operations?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Firm%2Frights%2Fwsdl%7DDocumentRoleOperationsService', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTROLEOPERATIONSSERVICE_WSDL_LOCATION = url;
    }

    public DocumentRoleOperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentRoleOperationsService() {
        super(DOCUMENTROLEOPERATIONSSERVICE_WSDL_LOCATION, new QName("http://xmlns.oracle.com/irm/rights/wsdl", "DocumentRoleOperationsService"));
    }

    /**
     * 
     * @return
     *     returns DocumentRoleOperations
     */
    @WebEndpoint(name = "DocumentRoleOperations")
    public DocumentRoleOperations getDocumentRoleOperations() {
        return super.getPort(new QName("http://xmlns.oracle.com/irm/rights/wsdl", "DocumentRoleOperations"), DocumentRoleOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentRoleOperations
     */
    @WebEndpoint(name = "DocumentRoleOperations")
    public DocumentRoleOperations getDocumentRoleOperations(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/irm/rights/wsdl", "DocumentRoleOperations"), DocumentRoleOperations.class, features);
    }

}
